export const projectsDB = [
  {
    name: "Compresses Files",
    summary: "Web application for compressing video files",
    tehcnologies: "React, Node JS, BootStrap",
    url: null,
    video_url: null,
    source_url: "https://github.com/farucis/compresses-files",
  },
  {
    name: "Accessibility",
    summary: "App for mute and deaf people",
    tehcnologies: "React Native, google-cloud-api",
    url: null,
    video_url: null,
    source_url: "https://github.com/farucis/Accessibility",
  },
  {
    name: "Test Cases",
    summary: "A web site for managing tests",
    tehcnologies: "React, Zustand, Firebase, BootStrap",
    url: "https://test-case-app-r.herokuapp.com/",
    video_url: null,
    source_url: "https://github.com/farucis/test-cases",
  },
  {
    name: "Shapeit",
    summary: "Daily Calorie Tracking",
    tehcnologies: "React-native, react-redux, firebase, Rest API, Python",
    url: "https://expo.dev/@faruch/Shapeit",
    video_url:
      "https://user-images.githubusercontent.com/58651410/169829260-d985197e-d167-48ce-9105-f3f6cd35f738.mp4",
    source_url: "https://github.com/farucis/Shapeit-Final",
  },
  {
    name: "Portfolio",
    summary: "My Persnoal Web Site",
    tehcnologies: "React, BootStrap",
    url: "https://portfolio-faruch.herokuapp.com/",
    video_url: null,
    source_url: "https://github.com/farucis/Portfolio-Faruch-I",
  },
  {
    name: "Recommendation System",
    summary: "CF/CBF and Hybrid Recommendation System ",
    tehcnologies: "Python, numpy, pandas, sklearn, matplotlib",
    url: null,
    video_url: null,
    source_url: "https://github.com/farucis/Hybrid-Recommendation-system",
  },
  {
    name: "Smart Book",
    summary: "Book Reding Web Site",
    tehcnologies: "asp.net, c#, sql server",
    url: null,
    video_url: null,
    source_url: "https://github.com/farucis/SmartBook-1",
  },
  {
    name: "Classification Manuscript",
    summary: "Classification Of Manuscript By Gender",
    tehcnologies: "Python, pandas, numpy, sklearn, skimage, tabulate",
    url: null,
    video_url: null,
    source_url:
      "https://github.com/farucis/Classification-of-manuscript-by-gender",
  },
  {
    name: "Scrum Master",
    summary: "Agile Project Management",
    tehcnologies: "React-native, react-redux, firebase",
    url: null,
    video_url: null,
    source_url: "https://github.com/farucis/ScruMaster",
  },
];
